### PR TITLE
add linkLabelFormat & linkLabelMinWidth arguments

### PR DESCRIPTION
**Pull request by dringler**
with default values from https://github.com/ricklupton/ipysankeywidget/blob/ff72925bf94bbf31ce7c791be53363e669f04a75/js/lib/sankey-widget.js#L47-L48 
can be passed when using the to_widget method.
solving issue 74: https://github.com/ricklupton/floweaver/issues/74

### CODE REVIEW

**Comment by ricklupton** [comment]
Thanks, I’ll have a look as soon as I can.

**Comment by ricklupton** [comment]
Sorry for the very long delay...
 
It would be good to name the attributes in Python consistently, i.e. `link_label_format` and `link_label_min_width`.

**Comment by dringler** [comment]
No worries. I updated the naming.

**Comment by ricklupton** [comment]
Thanks!

**Pull request merged**
